# Improved Model Configuration

model_name: improved_network

# Input image dimensions
image_height: 128
image_width: 128

# Classes
num_classes: 3
class_labels: ['pedestrian', 'rider', 'sitting person']

# Training parameters
num_epochs: 100
batch_size: 32
learning_rate: 0.001
weight_decay: 0.0001

# Dataset paths
train_dataset_path: data/processed/train
validation_dataset_path: data/processed/val

# Model save path
model_save_path: saved_models/improved
