# Oversampling Model Configuration

model_name: oversampling_network

# Input image dimensions
image_height: 128
image_width: 128

# Classes
num_classes: 3
class_labels: ['pedestrian', 'rider', 'sitting person']

# Class counts
class_counts:
  0: 2303
  1: 993
  2: 352

dataset_size:
  3648

# Oversampling factors
resampling_factors:
  0: 1 # 2303 / 2303 = 1 
  1: 3 # 2303 / 993 = 2.32 = 2
  2: 7 # 2303 / 352 = 6.54 = 7

# Training parameters
num_epochs: 100
batch_size: 32
learning_rate: 0.0001
weight_decay: 0.0001

# Dataset paths
train_dataset_path: data/processed/train
validation_dataset_path: data/processed/val
augmentation_save_dir: data/augmented

# Model save path
model_save_path: saved_models/oversampling
