# Weighted Cross Entropy Model Configuration

model_name: wce_network

# Input image dimensions
image_height: 128
image_width: 128

# Classes
num_classes: 3
class_labels: ['pedestrian', 'rider', 'sitting person']

# Class weights for weighted cross-entropy
class_weights: # normalised inverses of class probabilities
  0: 0.1014
  1: 0.2351
  2: 0.6635

# Training parameters
num_epochs: 100
batch_size: 32
learning_rate: 0.0001
weight_decay: 0.0001

# Dataset paths
train_dataset_path: data/processed/train
validation_dataset_path: data/processed/val

# Model save path
model_save_path: saved_models/wce
